"""Plugin pack import and registry management."""

from __future__ import annotations

import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .paths import (
    PLUGIN_REGISTRY_PATH,
    PLUGINS_DIR,
    PROVIDER_REGISTRY_PATH,
    REGISTRY_DIR,
    ROOT,
)
from .skill_importer import TRUST_LEVELS, slugify


PLUGIN_METADATA_FILES = ("plugin.json", "metadata.json")


@dataclass(frozen=True)
class PluginImportResult:
    """Result of importing a plugin pack."""

    plugin_name: str
    destination: Path
    provider: str
    trust_level: str
    overwritten: bool
    plugin_count: int
    provider_count: int


@dataclass(frozen=True)
class PluginTrustUpdateResult:
    """Result of updating a plugin trust level."""

    plugin_name: str
    metadata_path: Path
    old_trust_level: str | None
    new_trust_level: str
    plugin_count: int
    provider_count: int


def read_plugin_metadata(source: Path) -> dict[str, Any]:
    """Read plugin metadata from plugin.json or metadata.json."""
    for filename in PLUGIN_METADATA_FILES:
        path = source / filename
        if path.exists():
            return json.loads(path.read_text(encoding="utf-8"))
    return {}


def plugin_metadata_path(plugin_dir: Path) -> Path:
    """Return the canonical plugin metadata path."""
    return plugin_dir / "plugin.json"


def normalize_plugin_metadata(
    source: Path,
    destination: Path,
    provider: str,
    trust_level: str,
    source_url: str | None,
    name_override: str | None,
) -> dict[str, Any]:
    """Return normalized plugin metadata."""
    metadata = read_plugin_metadata(source)
    plugin_name = slugify(str(name_override or metadata.get("name") or source.name))

    metadata["name"] = plugin_name
    metadata.setdefault("title", " ".join(part.capitalize() for part in plugin_name.split("_")))
    metadata.setdefault("description", f"Imported plugin pack from {provider}.")
    metadata.setdefault("version", "0.1.0")
    metadata["provider"] = provider
    metadata["trust_level"] = trust_level
    metadata["status"] = trust_level
    metadata["path"] = destination.relative_to(ROOT).as_posix()
    metadata.setdefault("capabilities", discover_capabilities(destination))
    metadata["source"] = metadata.get("source", "imported")
    if source_url:
        metadata["source_url"] = source_url
    return metadata


def discover_capabilities(plugin_dir: Path) -> list[str]:
    """Infer plugin capabilities from known subdirectories."""
    capabilities: list[str] = []
    for name in ("skills", "prompts", "integrations", "commands", "adapters", "hooks"):
        if (plugin_dir / name).exists():
            capabilities.append(name)
    return capabilities


def copy_plugin_source(source: Path, destination: Path, overwrite: bool) -> bool:
    """Copy plugin source directory to destination."""
    if destination.exists():
        if not overwrite:
            raise FileExistsError(
                f"Destination already exists: {destination}. Use --overwrite to replace it."
            )
        shutil.rmtree(destination)
        overwritten = True
    else:
        overwritten = False

    shutil.copytree(source, destination)
    return overwritten


def list_plugin_metadata() -> list[dict[str, Any]]:
    """Read all plugin metadata files under plugins/."""
    plugins: list[dict[str, Any]] = []
    for metadata_path in sorted(PLUGINS_DIR.glob("**/plugin.json")):
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        metadata["path"] = metadata_path.parent.relative_to(ROOT).as_posix()
        metadata["capabilities"] = discover_capabilities(metadata_path.parent)
        plugins.append(metadata)
    return sorted(plugins, key=lambda item: item["name"])


def build_plugin_registry() -> dict[str, Any]:
    """Build the plugin registry document."""
    return {
        "schema_version": "1.0",
        "description": (
            "Plugin registry for the Personal AI Engineering OS. "
            "Generated by aios.plugins."
        ),
        "plugins": list_plugin_metadata(),
    }


def build_provider_registry(plugin_registry: dict[str, Any] | None = None) -> dict[str, Any]:
    """Build provider registry from plugin metadata."""
    plugin_registry = plugin_registry or build_plugin_registry()
    providers: dict[str, dict[str, Any]] = {}

    for plugin in plugin_registry.get("plugins", []):
        provider_name = plugin.get("provider", "unknown")
        provider = providers.setdefault(
            provider_name,
            {
                "name": provider_name,
                "plugin_count": 0,
                "plugins": [],
                "trust_levels": [],
            },
        )
        provider["plugin_count"] += 1
        provider["plugins"].append(plugin["name"])
        trust_level = plugin.get("trust_level", plugin.get("status", "untrusted"))
        if trust_level not in provider["trust_levels"]:
            provider["trust_levels"].append(trust_level)

    return {
        "schema_version": "1.0",
        "description": (
            "Provider registry for the Personal AI Engineering OS. "
            "Generated by aios.plugins."
        ),
        "providers": sorted(providers.values(), key=lambda item: item["name"]),
    }


def index_plugins() -> tuple[int, int]:
    """Write plugin and provider registries."""
    REGISTRY_DIR.mkdir(parents=True, exist_ok=True)
    plugin_registry = build_plugin_registry()
    provider_registry = build_provider_registry(plugin_registry)

    PLUGIN_REGISTRY_PATH.write_text(
        json.dumps(plugin_registry, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    PROVIDER_REGISTRY_PATH.write_text(
        json.dumps(provider_registry, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return len(plugin_registry["plugins"]), len(provider_registry["providers"])


def import_plugin(
    source_path: str | Path,
    provider: str = "community",
    trust_level: str = "untrusted",
    source_url: str | None = None,
    name: str | None = None,
    overwrite: bool = False,
) -> PluginImportResult:
    """Import a plugin pack into plugins/vendor/<provider>/<plugin_name>/."""
    if trust_level not in TRUST_LEVELS:
        supported = ", ".join(TRUST_LEVELS)
        raise ValueError(f"Unsupported trust level {trust_level!r}. Supported: {supported}")

    source = Path(source_path).expanduser().resolve()
    if not source.exists():
        raise FileNotFoundError(f"Plugin source does not exist: {source}")
    if not source.is_dir():
        raise NotADirectoryError(f"Plugin source must be a directory: {source}")

    metadata = read_plugin_metadata(source)
    plugin_name = slugify(str(name or metadata.get("name") or source.name))
    safe_provider = slugify(provider)
    destination = PLUGINS_DIR / "vendor" / safe_provider / plugin_name

    overwritten = copy_plugin_source(source, destination, overwrite)
    normalized = normalize_plugin_metadata(
        source=source,
        destination=destination,
        provider=safe_provider,
        trust_level=trust_level,
        source_url=source_url,
        name_override=plugin_name,
    )
    plugin_metadata_path(destination).write_text(
        json.dumps(normalized, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    plugin_count, provider_count = index_plugins()

    return PluginImportResult(
        plugin_name=normalized["name"],
        destination=destination,
        provider=safe_provider,
        trust_level=trust_level,
        overwritten=overwritten,
        plugin_count=plugin_count,
        provider_count=provider_count,
    )


def load_plugin_registry() -> dict[str, Any]:
    """Load plugin registry, generating it if needed."""
    if not PLUGIN_REGISTRY_PATH.exists():
        index_plugins()
    return json.loads(PLUGIN_REGISTRY_PATH.read_text(encoding="utf-8"))


def load_provider_registry() -> dict[str, Any]:
    """Load provider registry, generating it if needed."""
    if not PROVIDER_REGISTRY_PATH.exists():
        index_plugins()
    return json.loads(PROVIDER_REGISTRY_PATH.read_text(encoding="utf-8"))


def update_plugin_trust(plugin_name: str, trust_level: str) -> PluginTrustUpdateResult:
    """Update a plugin's trust_level and status metadata."""
    if trust_level not in TRUST_LEVELS:
        supported = ", ".join(TRUST_LEVELS)
        raise ValueError(f"Unsupported trust level {trust_level!r}. Supported: {supported}")

    matches = sorted(PLUGINS_DIR.glob(f"**/{plugin_name}/plugin.json"))
    if not matches:
        raise FileNotFoundError(f"No plugin metadata found for {plugin_name!r}")
    if len(matches) > 1:
        paths = ", ".join(path.relative_to(ROOT).as_posix() for path in matches)
        raise ValueError(f"Multiple plugin metadata files found for {plugin_name!r}: {paths}")

    metadata_path = matches[0]
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    old_trust_level = metadata.get("trust_level", metadata.get("status"))
    metadata["trust_level"] = trust_level
    metadata["status"] = trust_level

    metadata_path.write_text(
        json.dumps(metadata, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    plugin_count, provider_count = index_plugins()
    return PluginTrustUpdateResult(
        plugin_name=metadata["name"],
        metadata_path=metadata_path,
        old_trust_level=old_trust_level,
        new_trust_level=trust_level,
        plugin_count=plugin_count,
        provider_count=provider_count,
    )
