"""Skill registry indexing and validation."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .paths import REGISTRY_PATH, ROOT, SKILLS_DIR


REQUIRED_FIELDS = {
    "name",
    "title",
    "description",
    "path",
    "tags",
    "version",
    "status",
    "entrypoint",
}

TRUST_LEVELS = {"local", "reviewed", "vendor", "untrusted", "disabled"}


def load_registry(registry_path: Path = REGISTRY_PATH) -> dict[str, Any]:
    """Load the skill registry JSON document."""
    return json.loads(registry_path.read_text(encoding="utf-8"))


def registry_by_name(registry: dict[str, Any] | None = None) -> dict[str, dict[str, Any]]:
    """Return registry skills keyed by skill name."""
    registry = registry or load_registry()
    return {skill["name"]: skill for skill in registry.get("skills", [])}


def load_skill_metadata() -> list[dict[str, Any]]:
    """Load all skill metadata files under skills/."""
    skills: list[dict[str, Any]] = []

    for metadata_path in sorted(SKILLS_DIR.glob("**/metadata.json")):
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        skill_dir = metadata_path.parent
        metadata["path"] = skill_dir.relative_to(ROOT).as_posix()
        skills.append(metadata)

    return sorted(skills, key=lambda item: item["name"])


def build_registry() -> dict[str, Any]:
    """Build the in-memory skill registry."""
    return {
        "schema_version": "1.0",
        "description": (
            "Skill registry for the Personal AI Engineering OS. "
            "Generated by aios.registry."
        ),
        "skills": load_skill_metadata(),
    }


def index_skills() -> int:
    """Write registry/skills.json and return the number of indexed skills."""
    registry = build_registry()
    REGISTRY_PATH.parent.mkdir(parents=True, exist_ok=True)
    REGISTRY_PATH.write_text(
        json.dumps(registry, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return len(registry["skills"])


def find_brain_root(path: Path) -> Path:
    """Return the nearest engineering_brain root for a path."""
    current = path.resolve()
    if current.is_file():
        current = current.parent

    for candidate in [current, *current.parents]:
        if candidate.name == "engineering_brain":
            return candidate

    raise ValueError("Path is not inside an engineering_brain directory")


def validate_skill(skill_dir: Path) -> list[str]:
    """Return a list of validation errors for a skill directory."""
    errors: list[str] = []
    skill_dir = skill_dir.expanduser().resolve()

    if not skill_dir.exists():
        return [f"Skill directory does not exist: {skill_dir}"]
    if not skill_dir.is_dir():
        return [f"Skill path is not a directory: {skill_dir}"]

    metadata_path = skill_dir / "metadata.json"
    skill_path = skill_dir / "skill.md"

    if not metadata_path.exists():
        errors.append("Missing metadata.json")
    if not skill_path.exists():
        errors.append("Missing skill.md")

    if errors:
        return errors

    try:
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return [f"metadata.json is invalid JSON: {exc}"]

    missing_fields = sorted(REQUIRED_FIELDS - set(metadata))
    if missing_fields:
        errors.append(f"Missing metadata fields: {', '.join(missing_fields)}")

    if metadata.get("entrypoint") != "skill.md":
        errors.append("metadata.entrypoint should be skill.md")

    trust_level = metadata.get("trust_level")
    if trust_level is not None and trust_level not in TRUST_LEVELS:
        supported = ", ".join(sorted(TRUST_LEVELS))
        errors.append(f"metadata.trust_level must be one of: {supported}")

    status = metadata.get("status")
    if status in TRUST_LEVELS and trust_level is not None and status != trust_level:
        errors.append("metadata.status and metadata.trust_level should match")

    tags = metadata.get("tags")
    if tags is not None and not isinstance(tags, list):
        errors.append("metadata.tags must be a list")

    try:
        brain_root = find_brain_root(skill_dir)
        expected_path = skill_dir.relative_to(brain_root).as_posix()
        if metadata.get("path") != expected_path:
            errors.append(
                f"metadata.path should be {expected_path!r}, got {metadata.get('path')!r}"
            )
    except ValueError as exc:
        errors.append(str(exc))

    return errors


def skill_dirs() -> list[Path]:
    """Return all skill directories that contain metadata."""
    return sorted(metadata_path.parent for metadata_path in SKILLS_DIR.glob("**/metadata.json"))


def validate_all_skills() -> dict[str, list[str]]:
    """Validate all indexed skill directories and return errors by path."""
    results: dict[str, list[str]] = {}
    for skill_dir in skill_dirs():
        errors = validate_skill(skill_dir)
        if errors:
            results[skill_dir.relative_to(ROOT).as_posix()] = errors
    return results
